# Generated by Django 4.2.16 on 2024-10-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_feedback_created_at_groupcampaign_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigngroup',
            name='campaigns',
            field=models.ManyToManyField(through='app.GroupCampaign', to='app.campaign'),
        ),
        migrations.AddField(
            model_name='campaigngroup',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='groupcampaign',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_groups', to='app.campaign'),
        ),
        migrations.AlterField(
            model_name='groupcampaign',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_campaigns', to='app.campaigngroup'),
        ),
        migrations.AlterUniqueTogether(
            name='groupcampaign',
            unique_together={('group', 'campaign')},
        ),
        migrations.RemoveField(
            model_name='groupcampaign',
            name='created_at',
        ),
    ]
